name: Continuous Deployment

on:
    push:
      branches:
      - main
      - develop
    
jobs:
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest

    env:
      SOURCE_DIR: "build/"

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install

      - name: Build 
        run: npm run build 
